version: "3"
services:
  auth:
    build:
      context: auth/
      dockerfile: Dockerfile
    image: auth


  api:
    build:
      context: crud/
      dockerfile: Dockerfile
    image: crud


  gateway:
    build:
      context: gateway/
      dockerfile: Dockerfile
    ports:
      - 80:80


