version: "3"
services:
  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    image: auth
    networks:
      - mynetwork

  api:
    build:
      context: ./crud
      dockerfile: Dockerfile
    image: crud
    networks:
      - mynetwork

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile

    ports:
      - 80:80
    networks:
      - mynetwork


networks:
  mynetwork:
